AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - db/data_migrations/**/*
    - db/migrate/**/*
    - lib/tasks/**/*
    - config/initializers/**/*
Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Max: 250
Bundler/OrderedGems:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Max: 10
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 10
Naming/AccessorMethodName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/RescueEnsureAlignment:
   Enabled: false
Layout/IndentationStyle:
   Enabled: false
Style/MixinUsage:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/StderrPuts:
  Enabled: false  
Style/FormatStringToken:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Security/MarshalLoad:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Lint/Debugger:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Layout/EmptyLinesAroundArguments:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/MultilineArrayBraceLayout:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Lint/RescueException:
  Enabled: false
Lint/UnreachableCode:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: true
  Exclude:
    - spec/**/*
Style/FormatString:
  Enabled: false
Security/Eval:
  Enabled: false

Lint/Void:
  Enabled: true
  Exclude:
    - spec/**/*
