AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - db/data_migrations/**/*
    - db/migrate/**/*
    - lib/tasks/**/*
Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockNesting:
  Max: 5
Bundler/OrderedGems:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Max: 10
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 10
Naming/AccessorMethodName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Performance/Casecmp:
  Enabled: false
Layout/EmptyLinesAroundArguments:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Lint/RescueException:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: true
  Exclude:
    - spec/**/*
Style/FormatString:
  Enabled: false
Security/Eval:
  Enabled: false

Lint/Void:
  Enabled: true
  Exclude:
    - spec/**/*
